### ISSUE TITLE
ui icons not loading

### ISSUE THREAD

**Issue by stoponerr** [GreySux/googhud#2]
![image](https://github.com/GreySux/googhud/assets/33760451/77c29cd2-e3b1-49e9-b585-d8c2e8ff4319)
![image](https://github.com/GreySux/googhud/assets/33760451/73d0d6eb-c71d-4a91-adab-341caefb5a32)

**Comment by GreySux** [comment]
Are you playing on a language other than English?

**Comment by stoponerr** [comment]
no, language set to english in steam properties for the game.

**Comment by GreySux** [comment]
Unfortunately I haven't been able to recreate the issue. Is the HUD installed in your custom folder? Do you have anything else in your custom folder?

**Comment by stoponerr** [comment]
i removed all the other stuff from my custom folder and it didnt change, thanks for looking into this, i will just roll with it.
